name: GitHub Hosted Runners

on:
  push:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Print Runner Information
        run: |
          echo "===== Ubuntu Runner ====="
          echo "OS:"
          uname -a
          echo ""
          echo "Hostname:"
          hostname
          echo ""
          echo "Current User:"
          whoami

  windows:
    runs-on: windows-latest

    steps:
      - name: Print Runner Information
        shell: powershell
        run: |
          Write-Host "===== Windows Runner ====="
          systeminfo | findstr /B /C:"OS Name"
          Write-Host ""
          Write-Host "Hostname:"
          hostname
          Write-Host ""
          Write-Host "Current User:"
          whoami

  macos:
    runs-on: macos-latest

    steps:
      - name: Print Runner Information
        run: |
          echo "===== macOS Runner ====="
          sw_vers
          echo ""
          echo "Hostname:"
          hostname
          echo ""
          echo "Current User:"
          whoami
