name: Day 43 - Job Outputs

on:
  push:

jobs:
  generate_date:
    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.date.outputs.date }}

    steps:
      - name: Generate Today's Date
        id: date
        run: echo "date=$(date)" >> "$GITHUB_OUTPUT"

  display_date:
    needs: generate_date
    runs-on: ubuntu-latest

    steps:
      - name: Display Date
        run: echo "Today's date from previous job is: ${{ needs.generate_date.outputs.today }}"
