name: Day 44 - Secret Environment Variables

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret
        env:
          SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "Secret has been passed as an environment variable"
          if [ -n "$SECRET_MESSAGE" ]; then
            echo "Secret environment variable is available"
          else
            echo "Secret environment variable is not available"
            exit 1
          fi
