name: Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  self-hosted-job:
    runs-on: [self-hosted, my-linux-runner]

    steps:
      - uses: actions/checkout@v4

      - name: Show Hostname
        run: hostname

      - name: Show Working Directory
        run: pwd

      - name: Create File
        run: |
          touch myfile.txt
          ls -l
